pipeline {
  agent { kubernetes { yamlFile 'streaming-platform/jenkins/agent-pod.yaml' } }
  environment {
    REGISTRY = 'asia-south1-docker.pkg.dev/devops-1-502311/streaming-images'
    SVC = 'api-gateway'
    IMAGE = "${REGISTRY}/api-gateway:${GIT_COMMIT}"
  }
  stages {
    stage('Checkout') { steps { checkout scm } }
    stage('SonarQube') {
       steps { container('tools') {
         withSonarQubeEnv('sonar') { sh 'echo run sonar-scanner here' }
      } }
        }
    }
}
    }
//    stage('Quality Gate') { steps { timeout(time: 10, unit: 'MINUTES') { waitForQualityGate abortPipeline: true } } }
    stage('Build (kaniko)') {
      steps { container('kaniko') {
        sh "/kaniko/executor --dockerfile=services/${SVC}/Dockerfile --context=services/${SVC} --no-push --tarPath=/workspace/img.tar --destination=${IMAGE}"
      } }
    }
    stage('Trivy') { steps { container('tools') { sh 'trivy image --input /workspace/img.tar --exit-code 1 --severity HIGH,CRITICAL' } } }
    stage('Push (kaniko)') { steps { container('kaniko') { sh "/kaniko/executor --dockerfile=services/${SVC}/Dockerfile --context=services/${SVC} --destination=${IMAGE}" } } }
    stage('Approval') { steps { input message: 'Deploy to dev?', ok: 'Ship it' } }
    stage('GitOps commit') {
      steps { container('tools') {
        withCredentials([usernamePassword(credentialsId: 'github-pat', usernameVariable: 'U', passwordVariable: 'P')]) {
          sh '''
            yq -i ".image.tag = \"${GIT_COMMIT}\"" gitops/environments/dev/values.yaml
            git config user.email ci@lab && git config user.name jenkins
            git commit -am "ci: deploy ${SVC} ${GIT_COMMIT}"
            git push https://$U:$P@github.com/YOUR_GH/streaming-platform.git HEAD:main
          '''
        }
      } }
    }
  }
}
