{{- if gt (int .Values.replicaCount) 1 }}
{{- range .Values.services }}
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata: { name: {{ .name }} }
spec:
  minAvailable: {{ $.Values.pdb.minAvailable }}
  selector: { matchLabels: { app: {{ .name }} } }
{{- end }}
{{- end }}
