services:
  - name: frontend
    image: { repository: asia-south1-docker.pkg.dev/devops-1-502311/streaming-images/frontend, tag: REPLACED_BY_CI }
    containerPort: 3000
  - name: api-gateway
    image: { repository: asia-south1-docker.pkg.dev/devops-1-502311/streaming-images/api-gateway, tag: REPLACED_BY_CI }
    containerPort: 8080
  - name: catalog-service
    image: { repository: asia-south1-docker.pkg.dev/devops-1-502311/streaming-images/catalog-service, tag: 1183342accef1a4a77c146249354be13a4bab0a5 }
    containerPort: 8091
  - name: user-service
    image: { repository: asia-south1-docker.pkg.dev/devops-1-502311/streaming-images/user-service, tag: REPLACED_BY_CI }
    containerPort: 8092
  - name: playback-service
    image: { repository: asia-south1-docker.pkg.dev/devops-1-502311/streaming-images/playback-service, tag: REPLACED_BY_CI }
    containerPort: 8093
